import { ElementRef, EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { SizeToken, Appearance } from '../../types/tokens';
import * as i0 from "@angular/core";
export declare class WaTextareaComponent implements ControlValueAccessor {
    private host;
    get normalizedAppearance(): string | undefined;
    label?: string;
    hint?: string;
    placeholder?: string;
    rows?: number;
    resize?: 'none' | 'vertical' | 'horizontal' | 'both' | 'auto';
    size?: SizeToken | string;
    appearance?: Appearance | string;
    name?: string;
    required?: boolean;
    minlength?: number;
    maxlength?: number;
    autocapitalize?: 'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';
    autocorrect?: string;
    autocomplete?: string;
    autofocus?: boolean;
    enterkeyhint?: 'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';
    spellcheck?: boolean;
    inputmode?: 'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url';
    readonly?: boolean;
    disabled?: boolean;
    withLabel?: boolean;
    withHint?: boolean;
    backgroundColor?: string;
    borderColor?: string;
    borderWidth?: string;
    boxShadow?: string;
    waFocus: EventEmitter<FocusEvent>;
    waFocusHyphen: EventEmitter<FocusEvent>;
    waBlur: EventEmitter<FocusEvent>;
    waBlurHyphen: EventEmitter<FocusEvent>;
    waInput: EventEmitter<Event>;
    waInputHyphen: EventEmitter<Event>;
    waChange: EventEmitter<Event>;
    waChangeHyphen: EventEmitter<Event>;
    waInvalid: EventEmitter<CustomEvent<any>>;
    waInvalidHyphen: EventEmitter<CustomEvent<any>>;
    valueChange: EventEmitter<string>;
    private _value;
    onChange: (_: any) => void;
    onTouched: () => void;
    constructor(host: ElementRef<HTMLElement>);
    writeValue(val: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    handleInput(event: Event): void;
    handleChange(event: Event): void;
    onFocus(event: FocusEvent): void;
    onBlur(event: FocusEvent): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<WaTextareaComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WaTextareaComponent, "wa-textarea", never, { "label": { "alias": "label"; "required": false; }; "hint": { "alias": "hint"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "rows": { "alias": "rows"; "required": false; }; "resize": { "alias": "resize"; "required": false; }; "size": { "alias": "size"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "name": { "alias": "name"; "required": false; }; "required": { "alias": "required"; "required": false; }; "minlength": { "alias": "minlength"; "required": false; }; "maxlength": { "alias": "maxlength"; "required": false; }; "autocapitalize": { "alias": "autocapitalize"; "required": false; }; "autocorrect": { "alias": "autocorrect"; "required": false; }; "autocomplete": { "alias": "autocomplete"; "required": false; }; "autofocus": { "alias": "autofocus"; "required": false; }; "enterkeyhint": { "alias": "enterkeyhint"; "required": false; }; "spellcheck": { "alias": "spellcheck"; "required": false; }; "inputmode": { "alias": "inputmode"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "withLabel": { "alias": "withLabel"; "required": false; }; "withHint": { "alias": "withHint"; "required": false; }; "backgroundColor": { "alias": "backgroundColor"; "required": false; }; "borderColor": { "alias": "borderColor"; "required": false; }; "borderWidth": { "alias": "borderWidth"; "required": false; }; "boxShadow": { "alias": "boxShadow"; "required": false; }; }, { "waFocus": "waFocus"; "waFocusHyphen": "wa-focus"; "waBlur": "waBlur"; "waBlurHyphen": "wa-blur"; "waInput": "waInput"; "waInputHyphen": "wa-input"; "waChange": "waChange"; "waChangeHyphen": "wa-change"; "waInvalid": "waInvalid"; "waInvalidHyphen": "wa-invalid"; "valueChange": "valueChange"; }, never, never, true, never>;
}
//# sourceMappingURL=textarea.component.d.ts.map